### ISSUE TITLE
If I were to disable every rule, would demand still be removed?

### ISSUE THREAD

**Issue by clmc99** [Estecka/mc-Shifting-Wares#13]
I'm looking for a mod that disables demand since it doesn't look like either Infinite Village Trading or Villager Tweaks will be updated to 1.21. Would this mod still remove demand if all game rules are disabled?

**Comment by Estecka** [comment]
No, this mod has no effect at all when the rules are disabled.

Whatever this mod does to demand is really an unintended side-effect, and not a actual feature. Even with some rule enabled, there's no garantee Demand would be fully disabled. Demand is reset for a slot whenever it is rerolled, but until then, the current trade can still accrue some demand.
