### ISSUE TITLE
Does not work with VillagerConfig Mod

### ISSUE THREAD

**Issue by lumagatto** [Estecka/mc-Shifting-Wares#6]
Vanilla trades reappear after a trade reset

**Comment by Estecka** [comment]
Looks like the kind of mod that overrules built-in systems in favor of their own implementation. Those are pretty much guaranteed to be incompatible with other mods that rely on the overidden system. (For instance, the way trades are stored in memory.)

Making those two mods compatible will probably require a solution that is custom-made for VC. How easy that will be depends on how much they have changed: did only the address change, do they still use Mojang's trade factories, or do they use a completely different data structure.

**Comment by Estecka** [comment]
@lumagatto Which version are you playing on ?
I'll try to get something functional out soon, but I won't build for every version just yet.

**Comment by Estecka** [comment]
Sister issue: https://github.com/DrexHD/VillagerConfig/issues/38
(So I can have a quick link)

**Comment by Estecka** [comment]
A compatibility addon is now available [here](https://modrinth.com/mod/shiftingwares-villagerconfig-addon) for Shifting Wares 2.0
